name: Node.js CI

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get testing lib
      run: set -eu && git clone https://github.com/Yandex-Practicum/tests-second-floor.git
    - name: Check pull request link
      run: bash tests-second-floor/1_sprint/check_github_link.sh
    - name: Check npm run start existence
      run: bash tests-second-floor/1_sprint/check_start.sh
    - name: Check Parcel in start script
      run: bash tests-second-floor/1_sprint/check_parcel.sh
    - name: Check PORT 3000
      run: bash tests-second-floor/1_sprint/check_port.sh
    - name: Check routing
      run: node tests-second-floor/1_sprint/check_routing.js
#    - name: Check linters
#     run: npm -s i --prefix tests-second-floor/1_sprint && node tests-second-floor/1_sprint/check_lint.js
